<?php

$investors = array(
    array(
        'name' => 'John Doe',
        'description' => 'John Doe is a very successful investor. He has invested in many companies and has a lot of experience in the field. He is a very good person to work with and has a lot of knowledge about the industry.',
        'Country' => 'us',
        'type' => 'angel-investor',
        'total_value' => '1m-to-10m',
        'no_of_stocks' => '1-to-10',
        'turnover_ratio' => 'less-than-10',
    ),
    array(
        'name' => 'Jane Smith',
        'description' => 'Jane Smith has a broad portfolio and specializes in tech startups. She is known for her strategic insights and passion for innovation.',
        'Country' => 'ca',
        'type' => 'venture-capitalist',
        'total_value' => '1m-to-10m',
        'no_of_stocks' => '11-to-50',
        'turnover_ratio' => '10-to-20',
    ),
    array(
        'name' => 'Mark Johnson',
        'description' => 'Mark Johnson has invested in a diverse set of industries, ranging from real estate to technology. His long-term approach has made him highly respected.',
        'Country' => 'uk',
        'type' => 'private-equity',
        'total_value' => '10m-to-50m',
        'no_of_stocks' => '1-to-10',
        'turnover_ratio' => '20-to-50',
    ),
    array(
        'name' => 'Emily Brown',
        'description' => 'Emily Brown is passionate about green technologies and sustainable investment. She has helped many startups grow successfully.',
        'Country' => 'au',
        'type' => 'impact-investor',
        'total_value' => '10m-to-50m',
        'no_of_stocks' => '11-to-50',
        'turnover_ratio' => '20-to-50',
    ),
    array(
        'name' => 'David Lee',
        'description' => 'David Lee has a deep understanding of the Asian market and has made significant investments in emerging technologies.',
        'Country' => 'sg',
        'type' => 'venture-capitalist',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => '1-to-10',
        'turnover_ratio' => 'greater-than-50',
    ),
    array(
        'name' => 'Sarah Miller',
        'description' => 'Sarah Miller is an angel investor focused on health and wellness startups. She has been instrumental in the success of many early-stage companies.',
        'Country' => 'us',
        'type' => 'angel-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => '11-to-50',
        'turnover_ratio' => '10-to-20',
    ),
    array(
        'name' => 'Robert Taylor',
        'description' => 'Robert Taylor is a private equity investor who focuses on mid-market companies. He is known for his ability to scale businesses effectively.',
        'Country' => 'de',
        'type' => 'private-equity',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => '11-to-50',
        'turnover_ratio' => '10-to-20',
    ),
    array(
        'name' => 'Linda Wilson',
        'description' => 'Linda Wilson has invested in numerous real estate projects and has a strong background in property management and development.',
        'Country' => 'fr',
        'type' => 'real-estate-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => 'less-than-10',
    ),
    array(
        'name' => 'Paul Harris',
        'description' => 'Paul Harris is an experienced angel investor with a knack for identifying undervalued businesses and turning them around.',
        'Country' => 'us',
        'type' => 'angel-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => 'less-than-10',
    ),
    array(
        'name' => 'Nancy King',
        'description' => 'Nancy King is a seasoned venture capitalist known for her early-stage investments in the fintech space.',
        'Country' => 'ca',
        'type' => 'venture-capitalist',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => '10-to-20',
    ),
    array(
        'name' => 'Michael Scott',
        'description' => 'Michael Scott is a real estate investor who focuses on commercial properties. He is a strategic thinker and an expert in maximizing returns.',
        'Country' => 'us',
        'type' => 'real-estate-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => 'less-than-10',
    ),
    array(
        'name' => 'Susan Green',
        'description' => 'Susan Green is a private equity investor who specializes in healthcare investments. She is known for her patience and long-term vision.',
        'Country' => 'au',
        'type' => 'private-equity',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => 'less-than-10',
    ),
    array(
        'name' => 'James White',
        'description' => 'James White is a venture capitalist who invests primarily in artificial intelligence and machine learning startups.',
        'Country' => 'us',
        'type' => 'venture-capitalist',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => '10-to-20',
    ),
    array(
        'name' => 'Patricia Adams',
        'description' => 'Patricia Adams is an impact investor with a focus on sustainable agriculture. She has a reputation for making a difference in the world through her investments.',
        'Country' => 'uk',
        'type' => 'impact-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => '20-to-50',
    ),
    array(
        'name' => 'William Clark',
        'description' => 'William Clark is a well-known investor in the technology sector, with a specific focus on blockchain and cryptocurrency.',
        'Country' => 'de',
        'type' => 'tech-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => 'greater-than-50',
    ),
    array(
        'name' => 'Angela Mitchell',
        'description' => 'Angela Mitchell is a well-established angel investor known for her investments in early-stage retail and e-commerce companies.',
        'Country' => 'us',
        'type' => 'angel-investor',
        'total_value' => 'greater-than-50m',
        'no_of_stocks' => 'greater-than-100',
        'turnover_ratio' => 'less-than-10',
    ),
);

$options = array(
    'country' => array(
        'All' => 'all',
        'United States' => 'us',
        'United Kingdom' => 'uk',
        'Canada' => 'ca',
        'Australia' => 'au',
    ),
    'investor-type' => array(
        'All' => 'all',
        'Angel Investor' => 'angel-investor',
        'Venture Capitalist' => 'venture-capitalist',
        'Private Equity' => 'private-equity',
    ),
    'total-value' => array(
        'All' => 'all',
        '<$1M' => 'less-than-1m',
        '$1M-$10M' => '1m-to-10m',
        '$10M-$50M' => '10m-to-50m',
        '>$50M' => 'greater-than-50m',
    ),
    'num-stocks' => array(
        'All' => 'all',
        '1-10' => '1-to-10',
        '11-50' => '11-to-50',
        '51-100' => '51-to-100',
        '>100' => 'greater-than-100',
    ),
    'turnover-ratio' => array(
        'All' => 'all',
        '<10%' => 'less-than-10',
        '10%-20%' => '10-to-20',
        '20%-50%' => '20-to-50',
        '>50%' => 'greater-than-50',
    ),
);